"""add investments tables

Revision ID: 63fca2e63428
Revises: 20260620_0900
Create Date: 2026-06-24 21:54:14.688400
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision: str = '63fca2e63428'
down_revision: Union[str, None] = '20260620_0900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('investment_no', sa.String(length=60), nullable=False),
    sa.Column('investment_type', sa.String(length=40), nullable=False),
    sa.Column('institution_name', sa.String(length=200), nullable=False),
    sa.Column('instrument_name', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('invested_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('maturity_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investment_no', name='uq_investments_no')
    )
    op.create_index(op.f('ix_investments_invested_date'), 'investments', ['invested_date'], unique=False)
    op.create_index(op.f('ix_investments_investment_no'), 'investments', ['investment_no'], unique=False)
    op.create_index(op.f('ix_investments_investment_type'), 'investments', ['investment_type'], unique=False)
    op.create_index(op.f('ix_investments_maturity_date'), 'investments', ['maturity_date'], unique=False)
    op.create_index(op.f('ix_investments_status'), 'investments', ['status'], unique=False)
    op.create_table('investment_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('investment_id', sa.UUID(), nullable=False),
    sa.Column('trans_type', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('trans_date', sa.Date(), nullable=False),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_transactions_investment_id'), 'investment_transactions', ['investment_id'], unique=False)
    op.create_index(op.f('ix_investment_transactions_trans_date'), 'investment_transactions', ['trans_date'], unique=False)
    op.create_index(op.f('ix_investment_transactions_trans_type'), 'investment_transactions', ['trans_type'], unique=False)
    op.alter_column('collector_routes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('collector_routes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_collector_routes_assigned_collector_id'), 'collector_routes', ['assigned_collector_id'], unique=False)
    op.create_index(op.f('ix_collector_routes_status'), 'collector_routes', ['status'], unique=False)
    op.alter_column('field_collection_batches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('field_collection_batches', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_field_collection_batches_status'), 'field_collection_batches', ['status'], unique=False)
    op.alter_column('field_collection_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('field_collection_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('field_collection_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('field_collection_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_field_collection_batches_status'), table_name='field_collection_batches')
    op.alter_column('field_collection_batches', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('field_collection_batches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_collector_routes_status'), table_name='collector_routes')
    op.drop_index(op.f('ix_collector_routes_assigned_collector_id'), table_name='collector_routes')
    op.alter_column('collector_routes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('collector_routes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_investment_transactions_trans_type'), table_name='investment_transactions')
    op.drop_index(op.f('ix_investment_transactions_trans_date'), table_name='investment_transactions')
    op.drop_index(op.f('ix_investment_transactions_investment_id'), table_name='investment_transactions')
    op.drop_table('investment_transactions')
    op.drop_index(op.f('ix_investments_status'), table_name='investments')
    op.drop_index(op.f('ix_investments_maturity_date'), table_name='investments')
    op.drop_index(op.f('ix_investments_investment_type'), table_name='investments')
    op.drop_index(op.f('ix_investments_investment_no'), table_name='investments')
    op.drop_index(op.f('ix_investments_invested_date'), table_name='investments')
    op.drop_table('investments')
    # ### end Alembic commands ###
