"""add_qa_hardening_schema

Revision ID: 73a87c4b5e62
Revises: 63fca2e63428
Create Date: 2026-07-28 12:27:22.356470
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '73a87c4b5e62'
down_revision: Union[str, None] = '63fca2e63428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_loans_applied_by'), 'loans', ['applied_by'], unique=False)
    op.create_index(op.f('ix_loans_approved_by'), 'loans', ['approved_by'], unique=False)
    op.create_index(op.f('ix_loans_disbursed_by'), 'loans', ['disbursed_by'], unique=False)
    op.create_index(op.f('ix_loans_interest_method'), 'loans', ['interest_method'], unique=False)
    op.create_index(op.f('ix_loans_recommended_by'), 'loans', ['recommended_by'], unique=False)
    op.create_index(op.f('ix_loans_repayment_method'), 'loans', ['repayment_method'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loans_repayment_method'), table_name='loans')
    op.drop_index(op.f('ix_loans_recommended_by'), table_name='loans')
    op.drop_index(op.f('ix_loans_interest_method'), table_name='loans')
    op.drop_index(op.f('ix_loans_disbursed_by'), table_name='loans')
    op.drop_index(op.f('ix_loans_approved_by'), table_name='loans')
    op.drop_index(op.f('ix_loans_applied_by'), table_name='loans')
    # ### end Alembic commands ###
